# What is a Tensor?

A tensor is a generalization of vectors and matrices to potentially higher dimensions, see the Table below. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes. Each element in the Tensor has the same data type, and the data type is always known. Simply, tensor, in relation to machine learning, is a generalization of scalars, vectors and, matrices.
<br><br>
<center>
<img src= "https://cdn.iisc.talentsprint.com/AIandMLOps/Images/Intro_tensor.png" width=700px/>
</center>


In [ ]:
!pip install torch

In [ ]:
import torch
# Create a 3-dimensional tensor with random values from a uniform distribution
random_tensor = torch.rand(2, 3, 4)
print(random_tensor)

tensor([[[5.8663e-04, 4.6974e-01, 9.4295e-03, 3.3962e-01],
         [7.0443e-01, 6.2047e-01, 7.2292e-01, 6.2398e-01],
         [5.3263e-01, 2.3369e-01, 8.8927e-01, 3.7171e-01]],

        [[6.5798e-01, 6.6711e-01, 7.4737e-01, 7.6948e-01],
         [9.8122e-01, 1.8703e-01, 2.0808e-01, 1.2864e-01],
         [5.2671e-01, 2.6365e-01, 6.2520e-01, 4.5892e-01]]])


## Basic Mathematical Operations on Tensors





💥 Addition: Adds corresponding elements of tensors together, allowing for combining information or increasing values.

💥 Subtraction: Subtracts corresponding elements of tensors, useful for computing differences or detecting changes.

💥 Multiplication: Performs element-wise multiplication of tensors, enabling scaling or emphasizing certain features.
To perform matrix like multiplication of tensors: torch.matmul(tensor1, tensor2)

💥 Division: Divides corresponding elements of tensors, useful for normalization or finding relative proportions.

In [ ]:
import torch
# Create a base tensor
base_tensor = torch. tensor ([[1, 2], [3,4]])
# Create another tensor
second_tensor = torch.tensor ([[2, 2], [1,1]])
# Addition
addition_tensor = base_tensor + second_tensor
print("Addition: \\n", addition_tensor)
# Subtraction
subtraction_tensor = base_tensor - second_tensor
print("Subtraction: \\n", subtraction_tensor)
# Multiplication
multiplication_tensor = base_tensor * second_tensor
print("Multiplication: \\n", multiplication_tensor)
# Division
division_tensor = base_tensor / second_tensor
print("Division: In", division_tensor)


Addition: \n tensor([[3, 4],
        [4, 5]])
Subtraction: \n tensor([[-1,  0],
        [ 2,  3]])
Multiplication: \n tensor([[2, 4],
        [3, 4]])
Division: In tensor([[0.5000, 1.0000],
        [3.0000, 4.0000]])


## Tensor indexing and slicing

In [ ]:
import torch
# Create a tensor with size (2, 3, 3)
tensor = torch.tensor ([
	[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
	[[10, 11, 12], [13, 14, 15],[16, 17,18]]
])
print ("Original Tensor:")
print (tensor)
print("\\nTensor Shape:", tensor.shape)


Original Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
\nTensor Shape: torch.Size([2, 3, 3])


### Row Slice (Slice of the second row)

In [ ]:
# Row Slice (Slice of the second row)
row_slice = tensor[:, 1, :]
print("\\now Slice:")
print (row_slice)
print ("Row Slice Shape:", row_slice.shape)



\now Slice:
tensor([[ 4,  5,  6],
        [13, 14, 15]])
Row Slice Shape: torch.Size([2, 3])


### Column Slice (Slice of the third column)

In [ ]:
# Column Slice (Slice of the third column)
column_slice = tensor[:,:, 2]
print ("\\nColumn Slice:")
print(column_slice)
print ("Column Slice Shape:", column_slice.shape)


\nColumn Slice:
tensor([[ 3,  6,  9],
        [12, 15, 18]])
Column Slice Shape: torch.Size([2, 3])


### Mixed Slice

In [ ]:
# Mixed Slice (Mixed slice of rows and columns)
mixed_slice = tensor[:, 0:2, 1:3]
print("\\nMixed Slice:")
print (mixed_slice)
print("Mixed Slice Shape:", mixed_slice.shape)



\nMixed Slice:
tensor([[[ 2,  3],
         [ 5,  6]],

        [[11, 12],
         [14, 15]]])
Mixed Slice Shape: torch.Size([2, 2, 2])


## Reshaping and View in Tensors

In [ ]:
# Create a contiguous 2D tensor
tensor = torch. tensor([
	[1, 2, 3],
	[4, 5, 6]
])
# Reshape the tensor using view
reshaped_tensor = tensor.view(3, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [ ]:
import torch
# Create a non-contiguous 2D tensor using slicing
tensor = torch. tensor([[1, 2, 3, 4, 5, 6]])
sliced_tensor = tensor[:, :3]
# Reshape the tensor using reshape
reshaped_tensor = torch.reshape(sliced_tensor, (1, 3))
print ("Original Tensor:")
print (sliced_tensor)
print("\\nReshaped Tensor:")
print (reshaped_tensor)



Original Tensor:
tensor([[1, 2, 3]])
\nReshaped Tensor:
tensor([[1, 2, 3]])


## The -1 trick in view()

In [ ]:
import torch
# Create a tensor with size (2, 4)
tensor = torch. tensor([
	[1, 2, 3, 4],
	[5, 6, 7, 8]
])
# Reshape the tensor using view and -1 trick
reshaped_tensor = tensor.view(-1, 2)
print("Original Tensor:")
print (tensor)
print ("\\nReshaped Tensor:")
print (reshaped_tensor)


Original Tensor:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
\nReshaped Tensor:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
a= torch.ones(2,3,4)
b= a.view(1,4,-1)
print(b.shape)

torch.Size([1, 4, 6])


## Gradient calculation with Tensors

In [ ]:
import torch
# Enable gradient tracking
x = torch.tensor(3.0, requires_grad=True)
# Perform operations on the tensor
y = 2 * x + 1
z = y ** 2
# Compute gradients
z.backward()
# Access the computed gradients
x_grad = x.grad

print(x_grad)

tensor(28.)


## Detaching and no grad()

In [ ]:
import torch
# Create a tensor with tracking enabled
x = torch.tensor([3.0], requires_grad=True)
# Perform operations on the tensor
y = x**2 + 2*x + 1
# Stop tracking gradients using detach()
z = y.detach()
# Perform further operations without tracking
with torch.no_grad() :
  w = z * 2
print(w)



tensor([32.])
